### ISSUE TITLE
what's your train environment of  computer(hardware)?

### ISSUE THREAD

**Issue by BoyuanJiang** [vineetjain96/one-shot-mann#1]
Do you train the model use GPU?I tried to run your project to train it,but very slowly.So can you tell me your hardware and how much time you used to finish the whole training process?
thanks

**Comment by vineetjain96** [comment]
Hi Boyuan,
I have a NVIDIA GeForce GTX 960M with 4GB graphics memory which I used to train this model. This code does take some time to run even with the GPU and if I remember correctly, I had to train it for around 30 hours.

**Comment by BoyuanJiang** [comment]
thanks for reply.I have tried to use gpu but seem not faster than cpu.
