### ISSUE TITLE
One deviation from the paper

### ISSUE THREAD

**Issue by pipihou** [vineetjain96/one-shot-mann#2]
In your mann part ,it seems that you don't add new information to the memory but remove some memory.The relevant code is listed below
```
row_idx = tf.reshape(tf.tile(tf.reshape(wlu_tm1[:,0], shape=(-1, 1)), (1, self.memory_size[1])), [-1])
		row_idx += self.memory_size[0] * tf.reshape(tf.tile(tf.reshape(range(self.batch_size), shape=(-1, 1)), (1, self.memory_size[1])), [-1])
		col_idx = tf.tile(range(self.memory_size[1]), [self.batch_size])
		coords = tf.transpose(tf.stack([row_idx, col_idx]))
		binary_mask = tf.cast(tf.sparse_to_dense(coords, (self.batch_size*self.memory_size[0], self.memory_size[1]), 1), tf.bool)	
		M_t = tf.where(binary_mask, tf.constant(0., shape=(self.batch_size*self.memory_size[0], self.memory_size[1])), tf.reshape(M_tm1, shape=(self.batch_size*self.memory_size[0], self.memory_size[1])))
		M_t = tf.reshape(M_t,shape=(self.batch_size, self.memory_size[0], self.memory_size[1]))
```

**Comment by vineetjain96** [comment]
Thank you for pointing this out. I had written the code for adding new information to the memory, but somehow it got removed in the final version of the code.
I have made the necessary changes (just needed to add one line) and now it should be exactly as given in the paper.

**Comment by pipihou** [comment]
Thank you  for the fix. By the way, I still wonder why  M_t = M_t + tf.matmul(tf.transpose(ww_t, perm=[0,2,1]), k_t)  as M_t should be M_tm1 in the paper.I mention that you upgrade M_t with wlu_tm1 above ,but why?

**Comment by vineetjain96** [comment]
The memory update occurs in two steps:
1. Least used memory location is computed from wlu_tm1 and is set to zero
2. Writing to memory using ww_t and k_t
So, in the code, I upgrade M_tm1 with wlu_tm1 and name it M_t. Then I update this with ww_t and k_t. The end result is the same as described in the paper.

**Comment by vineetjain96** [comment]
Closing this. Hope my comments helped!
